Traceback (most recent call last):
  File "/home/mirai1/ppo-implementation-details/ppo.py", line 164, in <module>
    envs = gym.vector.SyncVectorEnv(
  File "/home/mirai1/anaconda3/envs/ppo_implementation_details/lib/python3.9/site-packages/gym/vector/sync_vector_env.py", line 34, in __init__
    self.envs = [env_fn() for env_fn in env_fns]
  File "/home/mirai1/anaconda3/envs/ppo_implementation_details/lib/python3.9/site-packages/gym/vector/sync_vector_env.py", line 34, in <listcomp>
    self.envs = [env_fn() for env_fn in env_fns]
  File "/home/mirai1/ppo-implementation-details/ppo.py", line 22, in thunk
    env = gym.wrappers.RecordVideo(env, "videos", record_video_trigger=lambda t : t % 1000 == 0)
TypeError: __init__() got an unexpected keyword argument 'record_video_trigger'